In [ ]:
# 여기서부터 ------------------------------------------------

In [1]:
import pandas as pd
import numpy as np
from konlpy.tag import Okt
import nltk
from konlpy.tag import Kkma
from konlpy.tag import Hannanum

df = pd.read_csv("23_환경에너지안전.csv", index_col = 0)
# 취업률 없는행 삭제
df = df.dropna(subset=['취업률'], how='any', axis=0)
df.reset_index(drop=True, inplace=True)
display(df)

,과정명,학원명,기간,훈련비,정원,취업률,연령대,지역1,지역2
0,폐수처리기술자 양성과정,중앙환경직업전문학교,73,3696190,29,85.8,34.0,대전,중구
1,"대기환경관리 기사, 산업기사 취득과정",금성기술직업전문학교,43,1488860,12,31.8,29.0,부산,부산진구
2,산업안전 필기,동부직업전문학교,30,556560,25,64.3,47.0,전남,순천시
3,수질환경관리인 양성 및 수질환경기사 산업기사 이론과정,신동성환경기술학원,58,2973950,20,38.5,23.0,서울,동작구
4,산업안전기사(산업기사)필기 및 실무,한국안전기술학원,35,939720,20,53.3,35.0,울산,남구
...,...,...,...,...,...,...,...,...,...
78,[태양광발전설비]태양광발전설비 및 전기공사,세종평생교육원,157,8962500,30,41.7,NaN,대구,북구
79,신재생(태양광) 및 내선공사 전기기능사 과정,인천대산전기직업학교,110,5520900,20,93.8,NaN,인천,부평구
80,태양광발전설비 및 전기공사 실무과정,경북산업직업전문학교,179,8933820,30,70.9,43.0,대구,동구
81,태양광발전시스템,대한상공회의소 경기인력개발원,177,8604000,30,85.7,NaN,경기,파주시
82,(태양광발전설비)태양광발전설비와 전기내선공사양성(비대면),부산산업직업전문학교,120,6595360,20,47.2,NaN,부산,연제구

In [2]:
df_c = df['과정명']
display(df_c)

# list_course = list(np.array(df_c.tolist()))
# str_course = '\n'.join(list_course)

# t = Hannanum() 
# tokens_ko = t.nouns(str_course) # 명사 토큰만 추출

# # 추출한 토큰으로 명사 객체 생성
# ko_ = nltk.Text(tokens_ko)       

# # 빈도수로 추출 후 딕셔너리로 저장
# freq_word = ko_.vocab()
# freq_dic = dict(freq_word)
# print(freq_dic)

0                        폐수처리기술자 양성과정
1                대기환경관리 기사, 산업기사 취득과정
2                             산업안전 필기
3       수질환경관리인 양성 및 수질환경기사 산업기사 이론과정
4                 산업안전기사(산업기사)필기 및 실무
                   ...
78            [태양광발전설비]태양광발전설비 및 전기공사
79           신재생(태양광) 및 내선공사 전기기능사 과정
80                태양광발전설비 및 전기공사 실무과정
81                           태양광발전시스템
82    (태양광발전설비)태양광발전설비와 전기내선공사양성(비대면)
Name: 과정명, Length: 83, dtype: object

In [3]:
comparelist = ['경영','평가','산업안전', '비파괴', '폐기물', '태양', '신재생', '광물','보건','관리', '컨설팅', '수질측정', '처리']
fixlist = ['환경경영','환경평가','산업안전관리', '비파괴검사', '폐기물관리', '태양광발전설비',
           '신재생에너지발전설비', '광물개발','환경보건관리','환경보건관리','환경보건관리', '수질분석가', '폐수처리기술자']

courselist = []
for i in range(len(df)) :
    for n in range(len(comparelist)) :
        if comparelist[n] in df_c[i] :
            course = fixlist[n]
            break;
        else :
            course = None
    courselist.append(course)

df['NCS'] = "23_환경에너지안전"
df['과정'] = courselist
display(df)


df.to_csv("preprocessing/23.csv")

,과정명,학원명,기간,훈련비,정원,취업률,연령대,지역1,지역2,NCS,과정
0,폐수처리기술자 양성과정,중앙환경직업전문학교,73,3696190,29,85.8,34.0,대전,중구,23_환경에너지안전,폐수처리기술자
1,"대기환경관리 기사, 산업기사 취득과정",금성기술직업전문학교,43,1488860,12,31.8,29.0,부산,부산진구,23_환경에너지안전,환경보건관리
2,산업안전 필기,동부직업전문학교,30,556560,25,64.3,47.0,전남,순천시,23_환경에너지안전,산업안전관리
3,수질환경관리인 양성 및 수질환경기사 산업기사 이론과정,신동성환경기술학원,58,2973950,20,38.5,23.0,서울,동작구,23_환경에너지안전,환경보건관리
4,산업안전기사(산업기사)필기 및 실무,한국안전기술학원,35,939720,20,53.3,35.0,울산,남구,23_환경에너지안전,산업안전관리
...,...,...,...,...,...,...,...,...,...,...,...
78,[태양광발전설비]태양광발전설비 및 전기공사,세종평생교육원,157,8962500,30,41.7,NaN,대구,북구,23_환경에너지안전,태양광발전설비
79,신재생(태양광) 및 내선공사 전기기능사 과정,인천대산전기직업학교,110,5520900,20,93.8,NaN,인천,부평구,23_환경에너지안전,태양광발전설비
80,태양광발전설비 및 전기공사 실무과정,경북산업직업전문학교,179,8933820,30,70.9,43.0,대구,동구,23_환경에너지안전,태양광발전설비
81,태양광발전시스템,대한상공회의소 경기인력개발원,177,8604000,30,85.7,NaN,경기,파주시,23_환경에너지안전,태양광발전설비
82,(태양광발전설비)태양광발전설비와 전기내선공사양성(비대면),부산산업직업전문학교,120,6595360,20,47.2,NaN,부산,연제구,23_환경에너지안전,태양광발전설비